// packages/vue/src/views/Signup/Index.vue
<template>
  <Page
    :title="
      isMainApp
        ? t('account.signup.title.account')
        : t('account.signup.title.user')
    "
    class="signup"
    :centered="true"
  >
    <div class="signup-content">
      <AccountSignupForm
        v-if="isMainApp"
        :loading="loading"
        @submit="handleSubmit"
      />
      <UserSignupForm v-else :loading="loading" @submit="handleSubmit" />
    </div>
  </Page>
</template>

<script setup lang="ts">
import { useConfig } from "@prefabs.tech/vue3-config";
import { useI18n } from "@prefabs.tech/vue3-i18n";
import { Page } from "@prefabs.tech/vue3-ui";
import { computed, inject, ref } from "vue";

import { signup } from "../../api/accounts";
import AccountSignupForm from "../../components/AccountSignupForm.vue";
import UserSignupForm from "../../components/UserSignupForm.vue";
import { useMyAccounts } from "../../composables/useMyAccounts";
import { SIGNUP_PATH_DEFAULT } from "../../constant";
import { useTranslations } from "../../index";

import type { User } from "../../types/account";
import type { SaasEventHandlers } from "../../types/plugin";
import type { AccountSignupData, UserSignupData } from "../../types/user";
import type { AppConfig } from "@prefabs.tech/vue3-config";

export interface SignupProperties {
  onSignupFailure?: (
    err?: unknown,
    data?: UserSignupData | AccountSignupData
  ) => Promise<void> | void;
  onSignupSuccess?: (
    res?: User,
    data?: UserSignupData | AccountSignupData
  ) => Promise<void> | void;
}

const props = withDefaults(defineProps<SignupProperties>(), {
  onSignupFailure: undefined,
  onSignupSuccess: undefined,
});

const config = useConfig() as AppConfig;
const messages = useTranslations();
const { t } = useI18n({ messages });

const myAccountsStore = useMyAccounts();
const isMainApp = computed(() => myAccountsStore.meta.isMainApp);

const saasConfig = inject<import("../../types/config").SaasConfig>(
  Symbol.for("saas.config")
);

if (!saasConfig) {
  throw new Error("SAAS config not provided");
}

const { apiPath = SIGNUP_PATH_DEFAULT, appRedirection = true } =
  saasConfig.accounts?.signup || {};

const loading = ref(false);

const __saasEventHandlers = Symbol.for("saas.eventHandlers");
const eventHandlers = inject<SaasEventHandlers>(__saasEventHandlers);

const handleSubmit = async (data: AccountSignupData | UserSignupData) => {
  loading.value = true;

  console.log('Index', data);

  try {
    const result = await signup({
      apiBaseUrl: config.apiBaseUrl,
      path: apiPath,
      data,
      accountSignup: isMainApp.value,
    });

    if (result) {
      if (props.onSignupSuccess) {
        await props.onSignupSuccess(result, data);
      }

      if (appRedirection && isMainApp.value && "slug" in data && data.slug) {
        const appUrl = `${window.location.protocol}//${data.slug}.${saasConfig.rootDomain}`;

        // FIXME Quick solution. Use a better way to handle redirection
        window.location.replace(appUrl);
      }
    }
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error("Signup failed:", error);

    if (props.onSignupFailure) {
      await props.onSignupFailure(error, data);
    }

    if (eventHandlers?.notification) {
      eventHandlers.notification({
        type: "error",
        message: t("account.signup.messages.error"),
      });
    }
  } finally {
    loading.value = false;
  }
};
</script>

<style scoped>
.signup-content {
  width: 100%;
}
</style>

// packages/react/src/views/Signup/index.tsx
import { useTranslation } from "@prefabs.tech/react-i18n";
import { AuthPage } from "@prefabs.tech/react-ui";
import { useState } from "react";

import { signup } from "@/api/accounts";
import { AccountSignupForm, UserSignupForm } from "@/components/Signup";
import { SIGNUP_PATH_DEFAULT } from "@/constants";
import { useAccounts, useConfig } from "@/hooks";
import { AccountSignupData, User, UserSignupData } from "@/types/account";

type SignupProperties = {
  onSignupFailure?: (
    err?: any, // eslint-disable-line @typescript-eslint/no-explicit-any
    data?: UserSignupData | AccountSignupData,
  ) => Promise<void> | void;
  onSignupSuccess?: (
    res?: User,
    data?: UserSignupData | AccountSignupData,
  ) => Promise<void> | void;
};

export const SignupPage = ({
  onSignupFailure,
  onSignupSuccess,
}: SignupProperties) => {
  const { t } = useTranslation("accounts");

  const {
    meta: { isMainApp },
  } = useAccounts();
  const { apiBaseUrl, accounts, rootDomain } = useConfig();

  const { apiPath = SIGNUP_PATH_DEFAULT, appRedirection = true } =
    accounts?.signup || {};

  const [loading, setLoading] = useState(false);

  const handleSubmit = (data: AccountSignupData | UserSignupData) => {
    setLoading(true);

    signup({ apiBaseUrl, path: apiPath, data })
      .then(async (result) => {
        if (result) {
          if (onSignupSuccess) {
            await onSignupSuccess(result, data);
          }

          if (appRedirection && "slug" in data && data.slug) {
            const appUrl = `${window.location.protocol}//${data.slug}.${rootDomain}`;

            // FIXME Quick solution. Use a better way to handle redirection
            window.location.replace(appUrl);
          }
        }
      })
      .catch(async (error) => {
        if (onSignupFailure) {
          await onSignupFailure(error, data);
        }
      })
      .finally(() => setLoading(false));
  };

  return (
    <AuthPage
      title={isMainApp ? t("signup.title.account") : t("signup.title.user")}
      centered
    >
      {isMainApp ? (
        <AccountSignupForm handleSubmit={handleSubmit} loading={loading} />
      ) : (
        <UserSignupForm handleSubmit={handleSubmit} loading={loading} />
      )}
    </AuthPage>
  );
};
