// packages/vue/src/components/AccountSignupForm.vue
<template>
  <div class="account-signup-form">
    <Form
      :initial-values="initialValues"
      :validation-schema="validationSchema"
      @submit="onSubmit"
    >
      <!-- Account Fields (Step 1) -->
      <div v-show="activeIndex === 0">
        <Input
          v-model="formData.name"
          :label="t('accounts.form.label.name')"
          name="name"
          type="text"
        />

        <template v-if="saasConfig.entity === 'both'">
          <SwitchInput
            v-model="formData.individual"
            :label="t('accounts.form.label.individual')"
            name="individual"
          />
        </template>

        <template v-if="shouldShowOrganizationFields">
          <Input
            v-model="formData.registeredNumber"
            :label="t('accounts.form.label.registeredNumber')"
            name="registeredNumber"
            type="text"
          />

          <Input
            v-model="formData.taxId"
            :label="t('accounts.form.label.taxId')"
            name="taxId"
            type="text"
          />
        </template>

        <template v-if="saasConfig.subdomains !== 'disabled'">
          <Input
            v-model="formData.slug"
            :label="t('accounts.form.label.slug')"
            name="slug"
            type="text"
          />

          <SwitchInput
            v-if="saasConfig.multiDatabase"
            v-model="formData.useSeparateDatabase"
            :label="t('accounts.form.label.useSeparateDatabase')"
            name="useSeparateDatabase"
          />
        </template>
      </div>

      <!-- User Fields (Step 2) -->
      <div v-if="activeIndex === 1">
        <div class="step-2-header">
          <button type="button" class="back-button" @click="activeIndex = 0">
            {{ t("account.signup.actions.previous") }}
          </button>
        </div>
        <UserSignupForm :loading="loading" @submit="handleUserSignupSubmit" />
      </div>

      <!-- Actions for Step 1 only -->
      <div v-if="activeIndex === 0" class="actions">
        <FormActions
          :actions="formActions"
          :loading="loading"
          alignment="filled"
          tabindex="0"
        />
      </div>
    </Form>
  </div>
</template>

<script setup lang="ts">
import { FormActions, Input, SwitchInput } from "@prefabs.tech/vue3-form";
import { useI18n } from "@prefabs.tech/vue3-i18n";
import { toFormValidator } from "@vee-validate/zod";
import { Form } from "vee-validate";
import { computed, inject, ref, watch } from "vue";
import { z } from "zod";

import UserSignupForm from "./UserSignupForm.vue";
import { useTranslations } from "../index";
import { createValidationSchemas } from "../views/Accounts/validations/accountValidations";

import type { SaasConfig } from "../types/config";
import type { AccountSignupData, UserSignupData } from "../types/user";

export interface AccountSignupFormProperties {
  loading?: boolean;
}

withDefaults(defineProps<AccountSignupFormProperties>(), {
  loading: false,
});

const emit = defineEmits<{
  submit: [userData: AccountSignupData];
}>();

const messages = useTranslations();
const { t } = useI18n({ messages });

const saasConfig = inject<SaasConfig>(Symbol.for("saas.config"));
if (!saasConfig) {
  throw new Error("SAAS config not provided");
}

const activeIndex = ref(0);

const { nameSchema, registeredNumberSchema, taxIdSchema, createSlugSchema } =
  createValidationSchemas();

const slugSchema = computed(() => createSlugSchema(saasConfig));

const formData = ref({
  // Account fields
  name: "",
  individual: saasConfig.entity === "individual",
  registeredNumber: "",
  taxId: "",
  slug: "",
  useSeparateDatabase: false,
  // User fields
  email: "",
  password: "",
  confirmPassword: "",
  termsAndConditions: false,
});

// Initial values for the form - matching React defaultValues
const initialValues = computed(() => ({
  name: formData.value.name,
  individual: formData.value.individual,
  registeredNumber: formData.value.registeredNumber,
  taxId: formData.value.taxId,
  slug: formData.value.slug,
  useSeparateDatabase: formData.value.useSeparateDatabase,
  email: formData.value.email,
  password: formData.value.password,
  confirmPassword: formData.value.confirmPassword,
  termsAndConditions: formData.value.termsAndConditions,
}));

const shouldShowOrganizationFields = computed(() => {
  if (saasConfig.entity === "organization") {
    return true;
  }

  if (saasConfig.entity === "both") {
    return !formData.value.individual;
  }

  return false;
});

// Account schema for step 1
const accountSchemaObject = computed(() => {
  const base = {
    name: nameSchema,
    individual: z.boolean(),
    registeredNumber: registeredNumberSchema.nullable(),
    taxId: taxIdSchema.nullable(),
    useSeparateDatabase: z.boolean().nullable(),
  };

  // Only include slug validation if subdomains is not disabled
  if (saasConfig.subdomains !== "disabled") {
    return {
      ...base,
      slug:
        saasConfig.subdomains === "required"
          ? slugSchema.value
          : z
              .string()
              .regex(
                /^(?!.*-+$)[\da-z][\da-z-]{0,23}([\da-z])?$/,
                t("accounts.form.validations.slug.invalid")
              )
              .nullable()
              .optional()
              .or(z.literal("")),
    };
  }

  return base;
});

const accountSchema = computed(() =>
  toFormValidator(z.object(accountSchemaObject.value))
);

const validationSchema = computed(() => accountSchema.value);

const formActions = computed(() => [
  {
    id: "next",
    label: t("account.signup.actions.next"),
    type: "submit",
  },
]);

watch(
  () => formData.value.individual,
  (newValue: boolean) => {
    if (newValue) {
      formData.value.registeredNumber = "";
      formData.value.taxId = "";
    }
  }
);

function onSubmit(validatedData: Record<string, unknown>) {
  // Step 1 submission - validate account fields and advance to step 2
  // Update formData with validated values from step 1
  if (validatedData.name) {
    formData.value.name = validatedData.name as string;
  }
  if (typeof validatedData.individual === "boolean") {
    formData.value.individual = validatedData.individual;
  }
  if (validatedData.registeredNumber !== undefined) {
    formData.value.registeredNumber = validatedData.registeredNumber as string;
  }
  if (validatedData.taxId !== undefined) {
    formData.value.taxId = validatedData.taxId as string;
  }
  if (validatedData.slug !== undefined) {
    formData.value.slug = validatedData.slug as string;
  }
  if (typeof validatedData.useSeparateDatabase === "boolean") {
    formData.value.useSeparateDatabase = validatedData.useSeparateDatabase;
  }

  activeIndex.value = 1;
}

function handleUserSignupSubmit(userData: UserSignupData) {
  // Step 2 submission - merge account data from step 1 with user data from UserSignupForm
  const accountData: AccountSignupData = {
    ...userData,
    name: formData.value.name,
    individual: formData.value.individual,
    registeredNumber: formData.value.registeredNumber || null,
    taxId: formData.value.taxId || null,
    slug: formData.value.slug || null,
    useSeparateDatabase: formData.value.useSeparateDatabase || null,
  };

  emit("submit", accountData);
}
</script>

<style lang="css">
.account-signup-form {
  width: 100%;
}

.account-signup-form .actions {
  display: contents;
}
</style>

// packages/react/src/components/accounts/Signup/AccountSignupForm.tsx
import { emailSchema, passwordSchema, Provider } from "@dzangolab/react-form";
import { useTranslation } from "@dzangolab/react-i18n";
import { useState } from "react";
import { z } from "zod";

import { useConfig } from "@/hooks";
import { AccountSignupData } from "@/types/account";

import { AccountFields } from "./AccountFields";
import { SignupFormActions } from "./SignupFormActions";
import { UserFields } from "./UserFields";

export type AccountSignupProperties = {
  loading?: boolean;
  handleSubmit: (formData: AccountSignupData) => void;
};

export const AccountSignupForm = ({
  loading,
  handleSubmit,
}: AccountSignupProperties) => {
  const { t } = useTranslation("accounts");

  const [activeIndex, setActiveIndex] = useState(0);

  const { accounts, subdomains } = useConfig();
  const { termsAndConditionsUrl } = accounts?.signup || {};

  const accountSchema = z.object({
    name: z
      .string()
      .max(255, {
        message: t("signup.validations.name.invalid"),
      })
      .min(1, {
        message: t("signup.validations.name.required"),
      }),
    individual: z.boolean(),
    organizationName: z
      .string()
      .max(255, {
        message: t("signup.validations.organizationName.invalid"),
      })
      .nullable(),
    registeredNumber: z
      .string()
      .max(255, {
        message: t("signup.validations.registeredNumber.invalid"),
      })
      .nullable(),
    taxId: z
      .string()
      .max(255, {
        message: t("signup.validations.taxId.invalid"),
      })
      .nullable(),
    slug:
      subdomains === "required"
        ? z
            .string()
            .regex(
              /^(?!.*-+$)[\da-z][\da-z-]{0,23}([\da-z])?$/,
              t("signup.validations.slug.invalid"),
            )
        : z
            .string()
            .regex(
              /^(?!.*-+$)[\da-z][\da-z-]{0,23}([\da-z])?$/,
              t("signup.validations.slug.invalid"),
            )
            .nullable()
            .optional()
            .or(z.literal("")),
    useSeparateDatabase: z.boolean().nullable(),
  });

  const userSchema = z.object({
    email: emailSchema({
      invalid: t("signup.validations.email.invalid"),
      required: t("signup.validations.email.required"),
    }),
    password: passwordSchema(
      {
        required: t("signup.validations.password.required"),
        weak: t("signup.validations.password.invalid"),
      },
      {
        minLength: 8,
        minLowercase: 1,
        minNumbers: 1,
        minSymbols: 0,
        minUppercase: 1,
      },
    ),
    confirmPassword: z
      .string()
      .min(1, t("signup.validations.confirmPassword.required")),
    ...(termsAndConditionsUrl
      ? {
          termsAndConditions: z.boolean().refine((value) => value === true, {
            message: t("signup.validations.termsAndConditions.required"),
          }),
        }
      : {}),
  });

  const accountSignupSchema = accountSchema.merge(userSchema).refine(
    (data) => {
      return data.password === data.confirmPassword;
    },
    {
      message: t("signup.validations.confirmPassword.mustMatch"),
      path: ["confirmPassword"],
    },
  );

  const onSubmit = (data: AccountSignupData) => {
    if (activeIndex === 1) {
      handleSubmit(data);
    } else {
      setActiveIndex(1);
    }
  };

  const onCancel = () => {
    setActiveIndex(0);
  };

  return (
    <>
      <Provider
        onSubmit={onSubmit}
        defaultValues={{
          // account fields
          individual: false,
          name: "",
          organizationName: "",
          registeredNumber: "",
          slug: "",
          taxId: "",
          useSeparateDatabase: false,

          // user fields
          email: "",
          password: "",
          confirmPassword: "",
        }}
        className="account-signup"
        validationSchema={
          activeIndex === 0 ? accountSchema : accountSignupSchema
        }
      >
        {activeIndex === 0 && <AccountFields />}
        {activeIndex === 1 && <UserFields />}
        <SignupFormActions
          submitButtonOptions={{
            label:
              activeIndex === 1
                ? t("signup.actions.submit")
                : t("signup.actions.next"),
            disabled: false, // FIXME disable submit only when user fields are shown
          }}
          cancelButtonOptions={{
            label: t("signup.actions.previous"),
            onClick: onCancel,
          }}
          loading={loading}
          showCancel={activeIndex === 1}
        />
      </Provider>
    </>
  );
};
