// packages/vue/src/components/SaasWrapper.vue
<template>
  <LoadingIcon v-if="loading" />

  <Page
    v-else-if="error && error.status === 404"
    class="error"
    :title="t('accounts.unregisteredDomain.title')"
    :subtitle="t('accounts.unregisteredDomain.message')"
    centered
  />

  <Page
    v-else-if="error"
    class="error"
    :title="t('accounts.error.title')"
    :subtitle="t('accounts.error.message')"
    centered
  />

  <ConfigProvider v-else :config="config">
    <SaasAccountsProvider
      v-if="!isAdminApp"
      :config="config"
      :user-id="props.userId"
    >
      <slot />
    </SaasAccountsProvider>
    <slot v-else />
  </ConfigProvider>
</template>

<script setup lang="ts">
import { useI18n } from "@prefabs.tech/vue3-i18n";
import { LoadingIcon, Page } from "@prefabs.tech/vue3-ui";
import { ref, onMounted, inject, defineProps } from "vue";

import { useTranslations } from "../index";
import ConfigProvider from "./ConfigProvider.vue";
import SaasAccountsProvider from "./SaasAccountsProvider.vue";
import { doesAccountExist } from "../api/accounts";
import { checkIsAdminApp } from "../utils/common";

import type { SaasConfig } from "../types/config";

export interface SaasWrapperProperties {
  userId?: string;
}

const props = defineProps<SaasWrapperProperties>();

// Get config from plugin injection
const config = inject<SaasConfig>(Symbol.for("saas.config"));

if (!config) {
  throw new Error(
    "SaasConfig not found! Make sure you've installed the SaaS Vue plugin with saasConfig."
  );
}

const messages = useTranslations();
const { t } = useI18n({ messages });

const loading = ref(true);
const error = ref<{ status?: number } | null>(null);

const isAdminApp = checkIsAdminApp();

onMounted(async () => {
  try {
    await doesAccountExist(config.apiBaseUrl);
  } catch (err) {
    error.value = err as { status?: number };
  } finally {
    loading.value = false;
  }
});
</script>

// packages/react/src/SaasWrapper.tsx
import { useTranslation } from "@prefabs.tech/react-i18n";
import { LoadingIcon, Page } from "@prefabs.tech/react-ui";
import { useEffect, useState } from "react";

import { SaasConfig } from "@/types";

import { doesAccountExist } from "./api";
import AccountsProvider from "./contexts/AccountsProvider";
import ConfigProvider from "./contexts/ConfigProvider";
import { checkIsAdminApp } from "./utils/common";

type SaasWrapperProperties = {
  config: SaasConfig;
  userId?: string;
  children: React.ReactNode;
};

export const SaasWrapper = ({
  config,
  userId,
  children,
}: SaasWrapperProperties) => {
  const [t] = useTranslation("accounts");

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<any>(); // eslint-disable-line @typescript-eslint/no-explicit-any

  useEffect(() => {
    doesAccountExist({ apiBaseUrl: config.apiBaseUrl })
      .then()
      .catch((error) => {
        setError(error);
      })
      .finally(() => {
        setLoading(false);
      });
  }, []);

  const isAdminApp = checkIsAdminApp();

  if (loading) {
    return <LoadingIcon />;
  }

  if (error) {
    if (error.status === 404) {
      return (
        <Page
          className="error"
          title={t("unregisteredDomain.title")}
          subtitle={t("unregisteredDomain.message")}
          centered
        ></Page>
      );
    } else {
      return (
        <Page
          className="error"
          title={t("error.title")}
          subtitle={t("error.message")}
          centered
        ></Page>
      );
    }
  }

  return (
    <ConfigProvider config={config}>
      {isAdminApp ? (
        children
      ) : (
        <AccountsProvider config={config} userId={userId}>
          {children}
        </AccountsProvider>
      )}
    </ConfigProvider>
  );
};
