// packages/vue/src/views/AcceptInvitation/JoinInvitation.vue
<template>
  <Page
    class="join-invitation"
    :title="t('account.joinInvitation.title')"
    :loading="invitationLoading || !invitation"
    :centered="centered"
  >
    <div v-if="error" class="error-message">
      <p>{{ t("account.joinInvitation.messages.errorFetching") }}</p>
    </div>

    <div v-else-if="isInvalidInvitation" class="error-message">
      <p>{{ t("account.joinInvitation.messages.invalid") }}</p>
    </div>

    <div v-else class="invitation-content">
      <p class="info">
        {{
          t("account.joinInvitation.info", {
            account: invitation?.account?.name || "",
          })
        }}
      </p>

      <div class="actions">
        <ButtonElement
          @click="handleSubmit"
          :loading="acceptLoading"
          class="accept-button"
        >
          {{ t("account.joinInvitation.actions.accept") }}
        </ButtonElement>

        <ButtonElement
          @click="handleIgnore"
          variant="outlined"
          severity="secondary"
          :disabled="acceptLoading"
          class="ignore-button"
        >
          {{ t("account.joinInvitation.actions.ignore") }}
        </ButtonElement>
      </div>
    </div>
  </Page>
</template>

<script setup lang="ts">
import { useConfig } from "@prefabs.tech/vue3-config";
import { useI18n } from "@prefabs.tech/vue3-i18n";
import { Page, ButtonElement } from "@prefabs.tech/vue3-ui";
import { ref, onMounted, computed, inject } from "vue";
import { useRoute, useRouter } from "vue-router";

import { useTranslations } from "../../index";
import useInvitationStore from "../../stores/accountInvitations";

import type { AccountInvitation } from "../../types/accountInvitation";
import type { SaasEventHandlers } from "../../types/plugin";
import type { AppConfig } from "@prefabs.tech/vue3-config";

export interface JoinInvitationProperties {
  centered?: boolean;
}

withDefaults(defineProps<JoinInvitationProperties>(), {
  centered: true,
});

const config = useConfig() as AppConfig;
const route = useRoute();
const router = useRouter();

const invitationStore = useInvitationStore();
const { getInvitationByToken, joinInvitation } = invitationStore;

const messages = useTranslations();
const { t } = useI18n({ messages });

const __saasEventHandlers = Symbol.for("saas.eventHandlers");
const eventHandlers = inject<SaasEventHandlers>(__saasEventHandlers);

const token = route.params.token as string;
const accountId = route.query.accountId as string | undefined;

const invitation = ref<AccountInvitation | null>(null);
const invitationLoading = ref(true);
const acceptLoading = ref(false);
const error = ref(false);

const isInvalidInvitation = computed(() => {
  if (!invitation.value) {
    return false;
  }

  return (
    invitation.value.acceptedAt ||
    invitation.value.revokedAt ||
    (invitation.value.expiresAt && invitation.value.expiresAt < Date.now())
  );
});

onMounted(async () => {
  if (token) {
    await fetchInvitation();
  }
});

async function fetchInvitation() {
  try {
    invitationLoading.value = true;
    error.value = false;
    const response = await getInvitationByToken(
      token,
      accountId || null,
      config.apiBaseUrl
    );
    invitation.value = response;
  } catch {
    error.value = true;
  } finally {
    invitationLoading.value = false;
  }
}

async function handleSubmit() {
  if (!token) {
    return;
  }

  try {
    acceptLoading.value = true;
    await joinInvitation(token, accountId || null, config.apiBaseUrl);

    // Show success notification
    if (eventHandlers?.notification) {
      eventHandlers.notification({
        type: "success",
        message: t("account.joinInvitation.messages.success"),
      });
    }

    // Navigate to home or wherever appropriate
    router.push("/");
  } catch {
    // Show error notification
    if (eventHandlers?.notification) {
      eventHandlers.notification({
        type: "error",
        message: t("account.joinInvitation.messages.error"),
      });
    }
  } finally {
    acceptLoading.value = false;
  }
}

function handleIgnore() {
  router.push("/");
}
</script>

<style lang="css">
.join-invitation {
  max-width: 400px;
  margin: 0 auto;
}

.join-invitation .error-message {
  text-align: center;
  color: var(--error-color, #dc3545);
  margin-bottom: 1rem;
}

.join-invitation .invitation-content {
  text-align: center;
}

.join-invitation .info {
  margin-bottom: 2rem;
  font-size: 1.1rem;
  line-height: 1.5;
}

.join-invitation .actions {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.join-invitation .accept-button {
  order: 1;
}

.join-invitation .ignore-button {
  order: 2;
}

@media (min-width: 768px) {
  .join-invitation .actions {
    flex-direction: row;
    justify-content: center;
  }

  .join-invitation .accept-button {
    order: 1;
  }

  .join-invitation .ignore-button {
    order: 2;
  }
}
</style>

// packages/react/src/views/AcceptInvitation/JoinInvitation.tsx
import { useTranslation } from "@prefabs.tech/react-i18n";
import { AuthPage, Button } from "@prefabs.tech/react-ui";
import { useEffect, useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { toast } from "react-toastify";

import { UseMutationRequestObject } from "@/api";
import {
  useAccounts,
  useGetInvitationQuery,
  useJoinInvitationMutation,
} from "@/hooks";
import { AcceptInvitationResponse } from "@/types";

export type JoinInvitationProperties = {
  centered?: boolean;
  onAcceptInvitationSuccess?: (
    response?: AcceptInvitationResponse,
    request?: UseMutationRequestObject<any>, // eslint-disable-line @typescript-eslint/no-explicit-any
  ) => void;
};

export const JoinInvitationPage = ({
  centered = true,
  onAcceptInvitationSuccess,
}: JoinInvitationProperties) => {
  const { refetchAccounts } = useAccounts();

  const { t } = useTranslation("accounts");
  const navigate = useNavigate();

  const { token } = useParams();
  const [searchParameters] = useSearchParams();
  const accountId = searchParameters.get("accountId");

  const [now, setNow] = useState<number | null>(null);

  const {
    data: invitation,
    loading: invitationLoading,
    error,
    trigger,
  } = useGetInvitationQuery(token!, accountId, {
    lazy: true,
  });

  useEffect(() => {
    queueMicrotask(() => setNow(Date.now()));
  }, []);

  const { loading: acceptLoading, trigger: triggerAcceptInvitation } =
    useJoinInvitationMutation({
      onSuccess: (response, request) => {
        onAcceptInvitationSuccess &&
          onAcceptInvitationSuccess(response, request);

        refetchAccounts();

        // TODO find a way to switch to newly joined account. cannot use switchAccount

        toast.success(t("joinInvitation.messages.success"));
        navigate("/");
      },
      onError: () => {
        toast.error(t("joinInvitation.messages.error"));
      },
    });

  useEffect(() => {
    if (token) {
      trigger();
    }
  }, [token, trigger]);

  const handleSubmit = () => {
    if (!token) {
      return;
    }

    triggerAcceptInvitation(token, accountId);
  };

  const handleIgnore = () => {
    navigate("/");
  };

  const renderPageContent = () => {
    if (error) {
      return <p>{t(`joinInvitation.messages.errorFetching`)}</p>;
    }

    if (
      invitation?.acceptedAt ||
      invitation?.revokedAt ||
      (now !== null && invitation?.expiresAt && invitation.expiresAt < now)
    ) {
      return <p>{t(`joinInvitation.messages.invalid`)}</p>;
    }

    return (
      <>
        <p className="info">
          {t("joinInvitation.info", {
            account: invitation?.account?.name || "",
          })}
        </p>
        <div className="actions">
          <Button onClick={handleSubmit} loading={acceptLoading}>
            {t(`joinInvitation.actions.accept`)}
          </Button>
          <Button
            onClick={handleIgnore}
            variant="outlined"
            severity="secondary"
            disabled={acceptLoading}
          >
            {t(`joinInvitation.actions.ignore`)}
          </Button>
        </div>
      </>
    );
  };

  return (
    <AuthPage
      className="join-invitation"
      title={t("joinInvitation.title")}
      loading={invitationLoading || !invitation}
      centered={centered}
    >
      {renderPageContent()}
    </AuthPage>
  );
};
